version: '3'
services:
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /Users/anthonyflori/Desktop/exodev/frontend:/app
    depends_on:
      - fastapi
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - /Users/anthonyflori/Desktop/exodev/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8081 --reload
